---
#
# Ansible managed
#
repository:
  description: Install and configure tfe on your system.
  homepage: https://buluma.github.io/
  topics: tfe, application, cloud, database, development, infrastructure, linux, monitoring, networking, storage, security, system, tools, windows, ansible, molecule, tox, playbook
