---
- become: true
  gather_facts: false
- name: Prepare
  hosts: all
  name: Prepare
  post_tasks:
    - ansible.builtin.service:
        enabled: true
        name: docker
        state: started
      name: Start docker daemon
  roles:
    - role: buluma.bootstrap
    - role: buluma.core_dependencies
    - role: buluma.docker_ce
    - role: buluma.docker_compose
